# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('blockchain', ['core'])
    module.source = [
        'model/blockchain.cc',
        'model/block.cc',
        'model/transaction.cc',
        # 'model/blockchain-node.cc',
        'helper/blockchain-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('blockchain')
    module_test.source = [
        'test/blockchain-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/blockchain-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'blockchain'
    headers.source = [
        'model/blockchain.h',
        'model/block.h',
        'model/transaction.h',
        'model/util.h',
        # 'model/blockchain-node.h',
        'helper/blockchain-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

